name: release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: denoland/setup-deno@v1
        with:
          deno-version: vx.x.x

      - uses: pnpm/action-setup@v2
        with:
          version: latest

      - uses: actions/setup-node@v2
        with:
          node-version: 16

      - run: deno run -A build.js
      - run: cat package.json
      - run: pnpm publish --access public --no-git-checks
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
